# Generated by Django 5.0.3 on 2024-07-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_userprofile_foto_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='foto',
            new_name='avatar',
        ),
    ]
