# Generated by Django 5.0.3 on 2024-07-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='media/default.jpg', upload_to='media'),
        ),
    ]
