# Generated by Django 5.0.3 on 2024-10-02 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_riddle_photo_1_riddle_photo_2_alter_riddle_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='acertijos_vistos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='match',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
