# Generated by Django 5.0.3 on 2024-10-03 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_match_acertijos_vistos_alter_match_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riddle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='riddle',
            name='song_url',
        ),
        migrations.AddField(
            model_name='riddle',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='songs'),
        ),
    ]
