# Generated by Django 5.0.3 on 2024-10-16 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_match_id_acertijo_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='partida_acabada',
            field=models.BooleanField(default=False),
        ),
    ]
