# Generated by Django 5.0.3 on 2024-10-22 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_match_partida_acabada'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='acertijo_corriente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='game.riddle'),
        ),
    ]
