# Generated by Django 5.0.3 on 2024-10-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_match_acertijo_corriente'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='acertijo_resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
